package wastedgames.proviant.enumerations;

public enum Image {
    ANT_WORK_0, ANT_WORK_1, ANT_WORK_2, ANT_WORK_3, ANT_WORK_4,
    ANT_WALK_0, ANT_WALK_1, ANT_WALK_2, ANT_WALK_3, ANT_WALK_4,
    TILE_DIRT_0, TILE_DIRT_1, TILE_DIRT_2, TILE_DIRT_3, TILE_DIRT_4,
    GRASS_0, GRASS_1, GRASS_2, GRASS_3, GRASS_4,
    GRASS_5, GRASS_6, GRASS_7, GRASS_8, GRASS_9,
    GRASS_10, GRASS_11, STICK_0, TILE_GRASS_0, TILE_GRASS_1,
    TILE_GRASS_2, TILE_GRASS_3, SNAIL_0, SNAIL_1, SNAIL_2,
    SNAIL_3, BACKGROUND_GRASS, DIRT_PILE_0, BUG_0, BUG_1,
    BUG_2, BUG_3, MEAT_0, MEAT_1, CHAMOMILE_0,
    CHAMOMILE_1, CHAMOMILE_2, CHAMOMILE_3, CHAMOMILE_4, CHAMOMILE_5,
    CHAMOMILE_6, CHAMOMILE_7, ROSE_0, ROSE_1, ROSE_2,
    ROSE_3, ROSE_4, ROSE_5, ROSE_6, ROSE_7,
    LADYBUG_0, LADYBUG_1, LADYBUG_2, LADYBUG_3, PROCESS_BAR_0,
    PROCESS_BAR_1, PROCESS_BAR_2, PROCESS_BAR_3, ANT_IDLE_0, STONE_0,
    SUN_0, LARVA_0, LARVA_1, LARVA_2, LARVA_3,
    LARVA_4, LARVA_5, ANT_CRAWL_0, BUG_CRAWL_0, DROP_FLY_0,
    DROP_FLY_1, DROP_FLY_2, DROP_LANDED_0, DROP_LANDED_1, DROP_LANDED_2,
    DROP_LANDED_3, DROP_LANDED_4, WORM_IDLE_0, WORM_MOVE_0, WORM_MOVE_1,
    WORM_MOVE_2, WORM_MOVE_3, WORM_MOVE_4, WORM_MOVE_5, CLOUD_0,
    CLOUD_1, CLOUD_2, CLOUD_3, CLOUD_4, TILE_TOP_GRASS,
    TILE_DIRT_BACK, TILE_DIRT_0_0, TILE_DIRT_0_1, TILE_DIRT_0_2, TILE_DIRT_0_3,
    TILE_DIRT_0_4, TILE_DIRT_0_5, TILE_DIRT_0_6, TILE_DIRT_0_7, TILE_DIRT_BACK_0,
    TILE_DIRT_BACK_1, TILE_DIRT_BACK_2, TILE_DIRT_BACK_3, NEST_0, TILE_STONE_0
}
