package wastedgames.proviant.enumerations;

public enum Image {
    ANT_WORK_0, ANT_WORK_1, ANT_WORK_2, ANT_WORK_3, ANT_WORK_4,
    ANT_WALK_0, ANT_WALK_1, ANT_WALK_2, ANT_WALK_3, ANT_WALK_4,
    TILE_DIRT_0, TILE_DIRT_1, TILE_DIRT_2, TILE_DIRT_3, TILE_DIRT_4,
    GRASS_0, GRASS_1, GRASS_2, GRASS_3, GRASS_4,
    GRASS_5, GRASS_6, GRASS_7, GRASS_8, GRASS_9,
    GRASS_10, GRASS_11, STICK_0, TILE_GRASS_0, TILE_GRASS_1,
    TILE_GRASS_2, TILE_GRASS_3, SNAIL_0, SNAIL_1, SNAIL_2,
    SNAIL_3, BACKGROUND_GRASS, DIRT_PILE_0, BUG_0, BUG_1,
    BUG_2, BUG_3, MEAT_0, MEAT_1
}
